In [1]:
from keras.models import Sequential
from keras.layers import Dense
import numpy


Using TensorFlow backend.


In [2]:
# training datas
train = numpy.array([
    [0, 0, 0],
    [0, 1, 1],
    [1, 0, 1],
    [1, 1, 0],
     [0, 0, 0],
    [0, 1, 1],
    [1, 0, 1],
    [1, 1, 0],
     [0, 0, 0],
    [0, 1, 1],
    [1, 0, 1],
    [1, 1, 0],
     [0, 0, 0],
    [0, 1, 1],
    [1, 0, 1],
    [1, 1, 0],
     [0, 0, 0],
    [0, 1, 1],
    [1, 0, 1],
    [1, 1, 0],
     [0, 0, 0],
    [0, 1, 1],
    [1, 0, 1],
    [1, 1, 0]
])
inputX = train[:, 0:2]
inputY = train[:, 2]

In [3]:
print(inputX)
print(inputY)

[[0 0]
 [0 1]
 [1 0]
 [1 1]
 [0 0]
 [0 1]
 [1 0]
 [1 1]
 [0 0]
 [0 1]
 [1 0]
 [1 1]
 [0 0]
 [0 1]
 [1 0]
 [1 1]
 [0 0]
 [0 1]
 [1 0]
 [1 1]
 [0 0]
 [0 1]
 [1 0]
 [1 1]]
[0 1 1 0 0 1 1 0 0 1 1 0 0 1 1 0 0 1 1 0 0 1 1 0]


In [4]:
# The sequential model is a linear stack of layers
model = Sequential()
model.add(Dense(2, input_dim=2))
model.add(Dense(3, activation='sigmoid'))
model.add(Dense(1))

In [5]:
model.compile(loss='mean_squared_error', optimizer='adam', metrics=['accuracy'])


In [6]:
model.fit(inputX, inputY, epochs=1000, batch_size=4)

Epoch 1/1000
24/24 [==============================] - 0s - loss: 2.7906 - acc: 0.0000e+00     
Epoch 2/1000
24/24 [==============================] - 0s - loss: 2.7080 - acc: 0.0000e+00     
Epoch 3/1000
24/24 [==============================] - 0s - loss: 2.6270 - acc: 0.0000e+00     
Epoch 4/1000
24/24 [==============================] - 0s - loss: 2.5479 - acc: 0.0000e+00     
Epoch 5/1000
24/24 [==============================] - 0s - loss: 2.4701 - acc: 0.0000e+00     
Epoch 6/1000
24/24 [==============================] - 0s - loss: 2.3920 - acc: 0.0000e+00     
Epoch 7/1000
24/24 [==============================] - 0s - loss: 2.3245 - acc: 0.0000e+00     
Epoch 8/1000
24/24 [==============================] - 0s - loss: 2.2517 - acc: 0.0000e+00     
Epoch 9/1000
24/24 [==============================] - 0s - loss: 2.1817 - acc: 0.0000e+00     
Epoch 10/1000
24/24 [==============================] - 0s - loss: 2.1160 - acc: 0.0000e+00     
Epoch 11/1000
24/24 [============================

24/24 [==============================] - 0s - loss: 0.3308 - acc: 0.5000     
Epoch 88/1000
24/24 [==============================] - 0s - loss: 0.3263 - acc: 0.5000     
Epoch 89/1000
24/24 [==============================] - 0s - loss: 0.3219 - acc: 0.5000     
Epoch 90/1000
24/24 [==============================] - 0s - loss: 0.3176 - acc: 0.5000     
Epoch 91/1000
24/24 [==============================] - 0s - loss: 0.3141 - acc: 0.5000         
Epoch 92/1000
24/24 [==============================] - 0s - loss: 0.3093 - acc: 0.5000     
Epoch 93/1000
24/24 [==============================] - 0s - loss: 0.3070 - acc: 0.5000     
Epoch 94/1000
24/24 [==============================] - 0s - loss: 0.3024 - acc: 0.5000     
Epoch 95/1000
24/24 [==============================] - 0s - loss: 0.2994 - acc: 0.5000     
Epoch 96/1000
24/24 [==============================] - 0s - loss: 0.2966 - acc: 0.5000     
Epoch 97/1000
24/24 [==============================] - 0s - loss: 0.2926 - acc: 0.5000    

24/24 [==============================] - 0s - loss: 0.2263 - acc: 0.5000     
Epoch 175/1000
24/24 [==============================] - 0s - loss: 0.2261 - acc: 0.5000     
Epoch 176/1000
24/24 [==============================] - 0s - loss: 0.2260 - acc: 0.5000     
Epoch 177/1000
24/24 [==============================] - 0s - loss: 0.2258 - acc: 0.5000     
Epoch 178/1000
24/24 [==============================] - 0s - loss: 0.2255 - acc: 0.5000     
Epoch 179/1000
24/24 [==============================] - 0s - loss: 0.2254 - acc: 0.5000     
Epoch 180/1000
24/24 [==============================] - 0s - loss: 0.2252 - acc: 0.5000     
Epoch 181/1000
24/24 [==============================] - 0s - loss: 0.2249 - acc: 0.5000     
Epoch 182/1000
24/24 [==============================] - 0s - loss: 0.2248 - acc: 0.5000     
Epoch 183/1000
24/24 [==============================] - 0s - loss: 0.2246 - acc: 0.5000     
Epoch 184/1000
24/24 [==============================] - 0s - loss: 0.2244 - acc: 0.50

24/24 [==============================] - 0s - loss: 0.2057 - acc: 0.7500     
Epoch 262/1000
24/24 [==============================] - 0s - loss: 0.2054 - acc: 0.7500     
Epoch 263/1000
24/24 [==============================] - 0s - loss: 0.2051 - acc: 0.7500     
Epoch 264/1000
24/24 [==============================] - 0s - loss: 0.2048 - acc: 0.7500     
Epoch 265/1000
24/24 [==============================] - 0s - loss: 0.2045 - acc: 0.7500     
Epoch 266/1000
24/24 [==============================] - 0s - loss: 0.2042 - acc: 0.7500     
Epoch 267/1000
24/24 [==============================] - 0s - loss: 0.2038 - acc: 0.7500     
Epoch 268/1000
24/24 [==============================] - ETA: 0s - loss: 0.2036 - acc: 0.750 - 0s - loss: 0.2035 - acc: 0.7500     
Epoch 269/1000
24/24 [==============================] - 0s - loss: 0.2032 - acc: 0.7500     
Epoch 270/1000
24/24 [==============================] - 0s - loss: 0.2030 - acc: 0.7500     
Epoch 271/1000
24/24 [=========================

24/24 [==============================] - 0s - loss: 0.1745 - acc: 0.7500     
Epoch 349/1000
24/24 [==============================] - 0s - loss: 0.1741 - acc: 0.7500     
Epoch 350/1000
24/24 [==============================] - 0s - loss: 0.1736 - acc: 0.7500     
Epoch 351/1000
24/24 [==============================] - ETA: 0s - loss: 0.1733 - acc: 0.750 - 0s - loss: 0.1733 - acc: 0.7500     
Epoch 352/1000
24/24 [==============================] - 0s - loss: 0.1728 - acc: 0.7500     
Epoch 353/1000
24/24 [==============================] - 0s - loss: 0.1725 - acc: 0.7500     
Epoch 354/1000
24/24 [==============================] - 0s - loss: 0.1721 - acc: 0.7500     
Epoch 355/1000
24/24 [==============================] - 0s - loss: 0.1718 - acc: 0.7500     
Epoch 356/1000
24/24 [==============================] - 0s - loss: 0.1712 - acc: 0.7500     
Epoch 357/1000
24/24 [==============================] - 0s - loss: 0.1710 - acc: 0.7500     
Epoch 358/1000
24/24 [=========================

24/24 [==============================] - 0s - loss: 0.1411 - acc: 1.0000     
Epoch 436/1000
24/24 [==============================] - 0s - loss: 0.1406 - acc: 1.0000     
Epoch 437/1000
24/24 [==============================] - 0s - loss: 0.1402 - acc: 1.0000     
Epoch 438/1000
24/24 [==============================] - 0s - loss: 0.1400 - acc: 1.0000     
Epoch 439/1000
24/24 [==============================] - 0s - loss: 0.1396 - acc: 1.0000     
Epoch 440/1000
24/24 [==============================] - 0s - loss: 0.1394 - acc: 1.0000     
Epoch 441/1000
24/24 [==============================] - 0s - loss: 0.1389 - acc: 1.0000     
Epoch 442/1000
24/24 [==============================] - 0s - loss: 0.1385 - acc: 1.0000     
Epoch 443/1000
24/24 [==============================] - 0s - loss: 0.1382 - acc: 1.0000     
Epoch 444/1000
24/24 [==============================] - 0s - loss: 0.1381 - acc: 1.0000     
Epoch 445/1000
24/24 [==============================] - 0s - loss: 0.1377 - acc: 1.00

24/24 [==============================] - 0s - loss: 0.1135 - acc: 1.0000     
Epoch 523/1000
24/24 [==============================] - 0s - loss: 0.1132 - acc: 1.0000     
Epoch 524/1000
24/24 [==============================] - 0s - loss: 0.1129 - acc: 1.0000     
Epoch 525/1000
24/24 [==============================] - 0s - loss: 0.1126 - acc: 1.0000     
Epoch 526/1000
24/24 [==============================] - 0s - loss: 0.1124 - acc: 1.0000     
Epoch 527/1000
24/24 [==============================] - 0s - loss: 0.1123 - acc: 1.0000     
Epoch 528/1000
24/24 [==============================] - 0s - loss: 0.1119 - acc: 1.0000     
Epoch 529/1000
24/24 [==============================] - 0s - loss: 0.1115 - acc: 1.0000     
Epoch 530/1000
24/24 [==============================] - 0s - loss: 0.1112 - acc: 1.0000     
Epoch 531/1000
24/24 [==============================] - 0s - loss: 0.1109 - acc: 1.0000     
Epoch 532/1000
24/24 [==============================] - 0s - loss: 0.1107 - acc: 1.00

24/24 [==============================] - 0s - loss: 0.0894 - acc: 1.0000     
Epoch 611/1000
24/24 [==============================] - 0s - loss: 0.0893 - acc: 1.0000     
Epoch 612/1000
24/24 [==============================] - 0s - loss: 0.0890 - acc: 1.0000     
Epoch 613/1000
24/24 [==============================] - 0s - loss: 0.0885 - acc: 1.0000     
Epoch 614/1000
24/24 [==============================] - 0s - loss: 0.0885 - acc: 1.0000     
Epoch 615/1000
24/24 [==============================] - 0s - loss: 0.0880 - acc: 1.0000     
Epoch 616/1000
24/24 [==============================] - 0s - loss: 0.0878 - acc: 1.0000     
Epoch 617/1000
24/24 [==============================] - 0s - loss: 0.0875 - acc: 1.0000     
Epoch 618/1000
24/24 [==============================] - 0s - loss: 0.0873 - acc: 1.0000     
Epoch 619/1000
24/24 [==============================] - 0s - loss: 0.0870 - acc: 1.0000     
Epoch 620/1000
24/24 [==============================] - 0s - loss: 0.0868 - acc: 1.00

24/24 [==============================] - 0s - loss: 0.0651 - acc: 1.0000     
Epoch 698/1000
24/24 [==============================] - 0s - loss: 0.0647 - acc: 1.0000     
Epoch 699/1000
24/24 [==============================] - 0s - loss: 0.0644 - acc: 1.0000     
Epoch 700/1000
24/24 [==============================] - 0s - loss: 0.0641 - acc: 1.0000     
Epoch 701/1000
24/24 [==============================] - 0s - loss: 0.0640 - acc: 1.0000     
Epoch 702/1000
24/24 [==============================] - 0s - loss: 0.0636 - acc: 1.0000     
Epoch 703/1000
24/24 [==============================] - 0s - loss: 0.0633 - acc: 1.0000     
Epoch 704/1000
24/24 [==============================] - 0s - loss: 0.0629 - acc: 1.0000     
Epoch 705/1000
24/24 [==============================] - 0s - loss: 0.0627 - acc: 1.0000     
Epoch 706/1000
24/24 [==============================] - 0s - loss: 0.0624 - acc: 1.0000     
Epoch 707/1000
24/24 [==============================] - 0s - loss: 0.0621 - acc: 1.00

24/24 [==============================] - 0s - loss: 0.0398 - acc: 1.0000     
Epoch 785/1000
24/24 [==============================] - 0s - loss: 0.0397 - acc: 1.0000     
Epoch 786/1000
24/24 [==============================] - 0s - loss: 0.0393 - acc: 1.0000     
Epoch 787/1000
24/24 [==============================] - 0s - loss: 0.0390 - acc: 1.0000     
Epoch 788/1000
24/24 [==============================] - 0s - loss: 0.0388 - acc: 1.0000     
Epoch 789/1000
24/24 [==============================] - 0s - loss: 0.0385 - acc: 1.0000     
Epoch 790/1000
24/24 [==============================] - 0s - loss: 0.0382 - acc: 1.0000     
Epoch 791/1000
24/24 [==============================] - 0s - loss: 0.0379 - acc: 1.0000     
Epoch 792/1000
24/24 [==============================] - 0s - loss: 0.0378 - acc: 1.0000     
Epoch 793/1000
24/24 [==============================] - 0s - loss: 0.0373 - acc: 1.0000     
Epoch 794/1000
24/24 [==============================] - 0s - loss: 0.0371 - acc: 1.00

24/24 [==============================] - 0s - loss: 0.0185 - acc: 1.0000     
Epoch 873/1000
24/24 [==============================] - 0s - loss: 0.0183 - acc: 1.0000     
Epoch 874/1000
24/24 [==============================] - 0s - loss: 0.0180 - acc: 1.0000     
Epoch 875/1000
24/24 [==============================] - 0s - loss: 0.0179 - acc: 1.0000     
Epoch 876/1000
24/24 [==============================] - 0s - loss: 0.0176 - acc: 1.0000     
Epoch 877/1000
24/24 [==============================] - 0s - loss: 0.0175 - acc: 1.0000     
Epoch 878/1000
24/24 [==============================] - 0s - loss: 0.0173 - acc: 1.0000     
Epoch 879/1000
24/24 [==============================] - 0s - loss: 0.0171 - acc: 1.0000     
Epoch 880/1000
24/24 [==============================] - 0s - loss: 0.0170 - acc: 1.0000     
Epoch 881/1000
24/24 [==============================] - 0s - loss: 0.0167 - acc: 1.0000     
Epoch 882/1000
24/24 [==============================] - 0s - loss: 0.0166 - acc: 1.00

24/24 [==============================] - 0s - loss: 0.0062 - acc: 1.0000     
Epoch 960/1000
24/24 [==============================] - 0s - loss: 0.0061 - acc: 1.0000     
Epoch 961/1000
24/24 [==============================] - 0s - loss: 0.0060 - acc: 1.0000     
Epoch 962/1000
24/24 [==============================] - 0s - loss: 0.0059 - acc: 1.0000     
Epoch 963/1000
24/24 [==============================] - 0s - loss: 0.0059 - acc: 1.0000     
Epoch 964/1000
24/24 [==============================] - 0s - loss: 0.0058 - acc: 1.0000     
Epoch 965/1000
24/24 [==============================] - ETA: 0s - loss: 0.0079 - acc: 1.000 - 0s - loss: 0.0057 - acc: 1.0000     
Epoch 966/1000
24/24 [==============================] - 0s - loss: 0.0056 - acc: 1.0000     
Epoch 967/1000
24/24 [==============================] - 0s - loss: 0.0055 - acc: 1.0000     
Epoch 968/1000
24/24 [==============================] - 0s - loss: 0.0054 - acc: 1.0000     
Epoch 969/1000
24/24 [=========================

In [7]:
scores = model.evaluate(inputX, inputY)
print("\n%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

24/24 [==============================] - 0s

acc: 100.00%


In [8]:
prediction = model.predict(numpy.array([[0,0], [0, 1], [1, 0], [0, 0]]))

In [9]:
print(prediction)

array([[ 0.0894355 ],
       [ 0.95265824],
       [ 0.96727258]], dtype=float32)

[0.0032671578228473663, 1.0]